<a href="https://colab.research.google.com/github/kanchandhole/Data-Scientist/blob/main/26_feb_assignments_numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

**Q1.** Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

**Ans:** list: it is python datatype
        
        array_list: it is numpy array

**Q2.** Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [3]:
import numpy as np
l =[1,2,3,4,5] #list
arr = np.array(l)#array_list
print(type(l))
print(type(arr))
print(l)
print(arr)

<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5]
[1 2 3 4 5]


**Q3. **Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)


In [5]:
list_ =[1,2,3,4,5]

In [7]:
Array_list = np.array(object = list_, dtype = int)
Array_list

array([1, 2, 3, 4, 5])

Consider the below code to answer further questions:

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

**Q4. **Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [8]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [9]:
num_array.shape

(2, 3)

In [10]:
num_array.size

6

**Q5.** Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [12]:
arr = np.array([[0,1,0],[1,0,1],[1,1,0]])
arr

array([[0, 1, 0],
       [1, 0, 1],
       [1, 1, 0]])

In [14]:
arr.shape

(3, 3)

In [13]:
arr.size

9

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [16]:
import numpy as np

# Create a 5x5 identity matrix using numpy.matrix
identity_matrix = np.matrix(np.identity(5))

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
